# Generated by Django 3.2.20 on 2023-07-09 21:24

from django.db import migrations
import multi_email_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0327_create_migrate_course_slug_config_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='watchers',
            field=multi_email_field.fields.MultiEmailField(blank=True, help_text='The email(s), one per line, where the report should be sent.', verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='watchers',
            field=multi_email_field.fields.MultiEmailField(blank=True, help_text='The email(s), one per line, where the report should be sent.', verbose_name='Email'),
        ),
    ]
