# Generated by Django 3.2.20 on 2023-07-10 20:42

from django.db import migrations
import multi_email_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0327_create_migrate_course_slug_config_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='watchers',
            field=multi_email_field.fields.MultiEmailField(blank=True, default=[], help_text='Email addresses of users who are watching this course', verbose_name='Watchers'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='watchers',
            field=multi_email_field.fields.MultiEmailField(blank=True, default=[], help_text='Email addresses of users who are watching this course', verbose_name='Watchers'),
        ),
    ]
